// generated by tscfg 0.3.0 on Tue Mar 01 22:05:09 PST 2016
// source: example/example-duration.spec.conf

package tscfg.example;

public class ExampleDurationCfg {
  public final Durations durations;
  public static class Durations {
    public final Long days;
    public final long hours;
    public final long millis;
    public Durations(com.typesafe.config.Config c) {
      this.days = c.hasPathOrNull("days") ? c.getDuration("days", java.util.concurrent.TimeUnit.DAYS) : null;
      this.hours = c.getDuration("hours", java.util.concurrent.TimeUnit.HOURS);
      this.millis = c.hasPathOrNull("millis") ? c.getDuration("millis", java.util.concurrent.TimeUnit.MILLISECONDS) : 550000;
    }
    public String toString() { return toString(""); }
    public String toString(String i) {
      return i+ "days = " + this.days + "\n"
          +i+ "hours = " + this.hours + "\n"
          +i+ "millis = " + this.millis + "\n";
    }
  }
  public ExampleDurationCfg(com.typesafe.config.Config c) {
    this.durations = new Durations(c.getConfig("durations"));
  }
  public String toString() { return toString(""); }
  public String toString(String i) {
    return i+ "durations {\n" + this.durations.toString(i+"    ") +i+ "}\n";
  }
}
