// generated by tscfg 0.3.4 on Sat Nov 19 11:07:01 PST 2016
// source: example/issue14.conf

package tscfg.example;

public class JavaIssue14Cfg {
  public final _0 _0;
  public static class _0 {
    public final java.lang.String _1;
    public _0(com.typesafe.config.Config c) {
      this._1 = c != null && c.hasPathOrNull("1") ? c.getString("1") : "bar";
    }
    public java.lang.String toString() { return toString(""); }
    public java.lang.String toString(java.lang.String i) {
      return i+ "_1 = " + this._1 + "\n";
    }
  }
  public final java.lang.String _2;
  public JavaIssue14Cfg(com.typesafe.config.Config c) {
    this._0 = new _0(__$config(c, "0"));
    this._2 = c != null && c.hasPathOrNull("2") ? c.getString("2") : "foo";
  }
  public java.lang.String toString() { return toString(""); }
  public java.lang.String toString(java.lang.String i) {
    return i+ "_0 {\n" + this._0.toString(i+"    ") +i+ "}\n"
        +i+ "_2 = " + this._2 + "\n";
  }
  private static com.typesafe.config.Config __$config(com.typesafe.config.Config c, java.lang.String path) {
    return c != null && c.hasPath(path) ? c.getConfig(path) : null;
  }
}
