// generated by tscfg 0.3.3 on Fri Aug 26 00:45:29 PDT 2016
// source: example/example-duration.spec.conf

package tscfg.example;

public class JavaExampleDurationCfg {
  public final Durations durations;
  public static class Durations {
    public final Long days;
    public final long hours;
    public final long millis;
    public Durations(com.typesafe.config.Config c) {
      this.days = c != null && c.hasPathOrNull("days") ? c.getDuration("days", java.util.concurrent.TimeUnit.DAYS) : null;
      this.hours = c.getDuration("hours", java.util.concurrent.TimeUnit.HOURS);
      this.millis = c != null && c.hasPathOrNull("millis") ? c.getDuration("millis", java.util.concurrent.TimeUnit.MILLISECONDS) : 550000;
    }
    public java.lang.String toString() { return toString(""); }
    public java.lang.String toString(java.lang.String i) {
      return i+ "days = " + this.days + "\n"
          +i+ "hours = " + this.hours + "\n"
          +i+ "millis = " + this.millis + "\n";
    }
    public java.lang.String toPropString() { return toPropString(""); }
    public java.lang.String toPropString(java.lang.String p) {
      return p+ "days = " + this.days + "\n"
          +p+ "hours = " + this.hours + "\n"
          +p+ "millis = " + this.millis + "\n";
    }
  }
  public JavaExampleDurationCfg(com.typesafe.config.Config c) {
    this.durations = new Durations(__$config(c, "durations"));
  }
  public java.lang.String toString() { return toString(""); }
  public java.lang.String toString(java.lang.String i) {
    return i+ "durations {\n" + this.durations.toString(i+"    ") +i+ "}\n";
  }
  public java.lang.String toPropString() { return toPropString(""); }
  public java.lang.String toPropString(java.lang.String p) {
    return this.durations.toPropString(p+"durations.");
  }
  private static com.typesafe.config.Config __$config(com.typesafe.config.Config c, java.lang.String path) {
    return c != null && c.hasPath(path) ? c.getConfig(path) : null;
  }
}
