// generated by tscfg 0.3.3 on Thu Aug 25 22:26:32 PDT 2016
// source: example/issue11.conf

package tscfg.example;

public class JavaIssue11Cfg {
  public final Foo foo;
  public static class Foo {
    public final String clone;
    public final String finalize;
    public final String getClass;
    public final String notify;
    public final String notifyAll;
    public final String toString;
    public final String wait;
    public Foo(com.typesafe.config.Config c) {
      this.clone = c != null && c.hasPathOrNull("clone") ? c.getString("clone") : "..";
      this.finalize = c != null && c.hasPathOrNull("finalize") ? c.getString("finalize") : "..";
      this.getClass = c != null && c.hasPathOrNull("getClass") ? c.getString("getClass") : "..";
      this.notify = c != null && c.hasPathOrNull("notify") ? c.getString("notify") : "..";
      this.notifyAll = c != null && c.hasPathOrNull("notifyAll") ? c.getString("notifyAll") : "..";
      this.toString = c != null && c.hasPathOrNull("toString") ? c.getString("toString") : "..";
      this.wait = c != null && c.hasPathOrNull("wait") ? c.getString("wait") : "..";
    }
    public String toString() { return toString(""); }
    public String toString(String i) {
      return i+ "clone = " + '"' + this.clone + '"' + "\n"
          +i+ "finalize = " + '"' + this.finalize + '"' + "\n"
          +i+ "getClass = " + '"' + this.getClass + '"' + "\n"
          +i+ "notify = " + '"' + this.notify + '"' + "\n"
          +i+ "notifyAll = " + '"' + this.notifyAll + '"' + "\n"
          +i+ "toString = " + '"' + this.toString + '"' + "\n"
          +i+ "wait = " + '"' + this.wait + '"' + "\n";
    }
  }
  public JavaIssue11Cfg(com.typesafe.config.Config c) {
    this.foo = new Foo(__$config(c, "foo"));
  }
  public String toString() { return toString(""); }
  public String toString(String i) {
    return i+ "foo {\n" + this.foo.toString(i+"    ") +i+ "}\n";
  }
  private static com.typesafe.config.Config __$config(com.typesafe.config.Config c, String path) {
    return c != null && c.hasPath(path) ? c.getConfig(path) : null;
  }
}
