// generated by tscfg 0.3.3 on Thu Aug 25 22:26:32 PDT 2016
// source: example/example1.spec.conf

package tscfg.example;

public class JavaExample1Cfg {
  public final String bazOptionalWithDefault;
  public final String bazOptionalWithNoDefault;
  public final String fooRequired;
  public JavaExample1Cfg(com.typesafe.config.Config c) {
    this.bazOptionalWithDefault = c != null && c.hasPathOrNull("bazOptionalWithDefault") ? c.getString("bazOptionalWithDefault") : "hello";
    this.bazOptionalWithNoDefault = c != null && c.hasPathOrNull("bazOptionalWithNoDefault") ? c.getString("bazOptionalWithNoDefault") : null;
    this.fooRequired = c.getString("fooRequired");
  }
  public String toString() { return toString(""); }
  public String toString(String i) {
    return i+ "bazOptionalWithDefault = " + '"' + this.bazOptionalWithDefault + '"' + "\n"
        +i+ "bazOptionalWithNoDefault = " + (this.bazOptionalWithNoDefault == null ? null : '"' + this.bazOptionalWithNoDefault + '"') + "\n"
        +i+ "fooRequired = " + '"' + this.fooRequired + '"' + "\n";
  }
}
