// generated by tscfg 0.3.3 on Thu Sep 01 11:12:22 PDT 2016
// source: example/issue12.conf

package tscfg.example;

public class JavaIssue12Cfg {
  public final Boolean Boolean;
  public static class Boolean {
    public final java.lang.String bar;
    public Boolean(com.typesafe.config.Config c) {
      this.bar = c != null && c.hasPathOrNull("bar") ? c.getString("bar") : "foo";
    }
    public java.lang.String toString() { return toString(""); }
    public java.lang.String toString(java.lang.String i) {
      return i+ "bar = " + this.bar + "\n";
    }
  }
  public final Option Option;
  public static class Option {
    public final java.lang.String bar;
    public Option(com.typesafe.config.Config c) {
      this.bar = c != null && c.hasPathOrNull("bar") ? c.getString("bar") : "baz";
    }
    public java.lang.String toString() { return toString(""); }
    public java.lang.String toString(java.lang.String i) {
      return i+ "bar = " + this.bar + "\n";
    }
  }
  public final String String;
  public static class String {
    public final java.lang.String bar;
    public String(com.typesafe.config.Config c) {
      this.bar = c != null && c.hasPathOrNull("bar") ? c.getString("bar") : "baz";
    }
    public java.lang.String toString() { return toString(""); }
    public java.lang.String toString(java.lang.String i) {
      return i+ "bar = " + this.bar + "\n";
    }
  }
  public final Int int_;
  public static class Int {
    public final int bar;
    public Int(com.typesafe.config.Config c) {
      this.bar = c != null && c.hasPathOrNull("bar") ? c.getInt("bar") : 1;
    }
    public java.lang.String toString() { return toString(""); }
    public java.lang.String toString(java.lang.String i) {
      return i+ "bar = " + this.bar + "\n";
    }
  }
  public JavaIssue12Cfg(com.typesafe.config.Config c) {
    this.Boolean = new Boolean(__$config(c, "Boolean"));
    this.Option = new Option(__$config(c, "Option"));
    this.String = new String(__$config(c, "String"));
    this.int_ = new Int(__$config(c, "int"));
  }
  public java.lang.String toString() { return toString(""); }
  public java.lang.String toString(java.lang.String i) {
    return i+ "Boolean {\n" + this.Boolean.toString(i+"    ") +i+ "}\n"
        +i+ "Option {\n" + this.Option.toString(i+"    ") +i+ "}\n"
        +i+ "String {\n" + this.String.toString(i+"    ") +i+ "}\n"
        +i+ "int_ {\n" + this.int_.toString(i+"    ") +i+ "}\n";
  }
  private static com.typesafe.config.Config __$config(com.typesafe.config.Config c, java.lang.String path) {
    return c != null && c.hasPath(path) ? c.getConfig(path) : null;
  }
}
