addSbtPlugin("com.eed3si9n"   % "sbt-assembly"  % "2.2.0")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype"  % "3.11.3")
addSbtPlugin("com.github.sbt" % "sbt-pgp"       % "2.1.2")
addSbtPlugin("org.scoverage"  % "sbt-scoverage" % "2.0.9")
addSbtPlugin("org.scoverage"  % "sbt-coveralls" % "1.3.13")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"  % "2.5.2")
addSbtPlugin("com.eed3si9n"   % "sbt-buildinfo" % "0.12.0")
