addSbtPlugin("com.eed3si9n"   % "sbt-assembly"  % "1.1.0")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype"  % "3.9.10")
addSbtPlugin("com.github.sbt" % "sbt-pgp"       % "2.1.2")
addSbtPlugin("org.scoverage"  % "sbt-scoverage" % "1.9.2")
addSbtPlugin("org.scoverage"  % "sbt-coveralls" % "1.3.1")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"  % "2.4.4")
