package tscfg.generators.java

import java.io.{FileWriter, PrintWriter}

import tscfg.generator._
import tscfg.generators.Generator
import tscfg.javaUtil._
import tscfg.specs._
import tscfg.specs.types._

import scala.annotation.tailrec

class JavaGenerator(implicit genOpts: GenOpts) extends Generator {

  def generate(objSpec: ObjSpec): GenResult = {

    var results = GenResult()

    def genForObjSpec(objSpec: ObjSpec, indent: String, isRoot: Boolean = false): Code = {
      // <class>
      val className = getClassName(objSpec.name)
      results = results.copy(classNames = results.classNames + className)

      val staticStr = if (isRoot) "" else " static"
      val code = Code(objSpec,
        javaType = className,
        javaId = javaIdentifier(objSpec.name),
        declaration = indent + "public final " + className + " " + javaIdentifier(objSpec.name) + ";"
      )

      code.println(indent + s"public$staticStr class $className {")

      // generate for members:
      val orderedNames = objSpec.children.keys.toList.sorted
      val codes = orderedNames map { name =>
        genCode(objSpec.children(name), indent + IND)
      }

      // member declarations:
      codes.map(_.declaration).filter(_.nonEmpty).foreach(code.println)

      // member definitions:
      val definitions = codes.map(_.definition).filter(_.nonEmpty)
      if (definitions.nonEmpty) {
        code.println("")
        definitions.foreach(code.print)
      }

      // <constructor>
      code.println("")
      code.println(indent + IND + s"public $className($TypesafeConfigClassName c) {")
      codes foreach { memberCode ⇒
        code.println(
          indent + IND + IND + "this." + memberCode.javaId +
            " = " + instance(memberCode.spec, memberCode.spec.name) + ";"
        )
      }
      code.println(indent + IND + "}")
      // </constructor>

      // auxiliary methods:
      accessors.insertAuxMethods(code, isRoot, indent + IND, results)

      code.println(indent + "}")
      // </class>

      code
    }

    def genForAtomicSpec(spec: AtomicSpec, indent: String): Code = {
      val javaId = javaIdentifier(spec.name)
      val javaType = getJavaType(spec)
      Code(spec,
        javaType,
        javaId = javaId,
        declaration = indent + "public final " + javaType + " " + javaId + ";")
    }

    def genForListSpec(listSpec: ListSpec, indent: String): Code = {
      @tailrec
      def listNesting(ls: ListSpec, levels: Int): (Spec, Int) = ls.elemSpec match {
        case subListSpec: ListSpec ⇒ listNesting(subListSpec, levels + 1)
        case nonListSpec           ⇒ (nonListSpec, levels)
      }

      val (elemSpec, levels) = listNesting(listSpec, 1)

      val elemCode = genCode(elemSpec, indent)
      println(s"\n\nelemCode:$elemCode\n\n")
      val elemObjType = toObjectType(elemCode.spec)
      val javaType = ("java.util.List<" * levels) + elemObjType + (">" * levels)
      val javaId = javaIdentifier(listSpec.name)
      val code = Code(listSpec, javaType, javaId)

      if (elemCode.definition.nonEmpty) code.println(elemCode.definition)

      code.declaration = indent + "public final " + javaType + " " + javaId + ";"
      code
    }

    def genCode(spec: Spec, indent: String = ""): Code = spec match {
      case spec: AtomicSpec    ⇒ genForAtomicSpec(spec, indent)
      case spec: ObjSpec       ⇒ genForObjSpec(spec, indent)
      case spec: ListSpec      ⇒ genForListSpec(spec, indent)
    }

    val header = new StringBuilder()
    //header.append(s"// generated by tscfg $version on ${new Date()}\n")
//    genOpts.preamble foreach { p =>
//      header.append(s"// ${p.replace("\n", "\n// ")}\n\n")
//    }
    header.append(s"package ${genOpts.packageName};\n\n")

    // main class:
    val elemSpec = genForObjSpec(objSpec, "", isRoot = true)

    results = results.copy(code = header.toString() + elemSpec.definition)

    results
  }

  private case class Code(
                  spec: Spec,
                  javaType: String,
                  javaId: String,
                  var declaration: String = ""
                 ) {
    def println(str: String): Unit = defn.append(str).append('\n')

    def print(str: String): Unit = defn.append(str)

    def definition = defn.toString

    private val defn = new StringBuilder()
  }

  private val IND = "    "

  private def getJavaType(spec: Spec): String = {
    spec match {
      case a: AtomicSpec ⇒
        a.typ match {
            case STRING   ⇒ "java.lang.String"
            case INTEGER  ⇒ if (spec.isOptional) "java.lang.Integer" else "int"
            case LONG     ⇒ if (spec.isOptional) "java.lang.Long"    else "long"
            case DOUBLE   ⇒ if (spec.isOptional) "java.lang.Double"  else "double"
            case BOOLEAN  ⇒ if (spec.isOptional) "java.lang.Boolean" else "boolean"
            case DURATION ⇒ if (spec.isOptional) "java.lang.Long"    else "long"
        }

      case o: ObjSpec  ⇒ getClassName(o.name)  // javaId

      case l: ListSpec  ⇒
        val elemJavaType = toObjectType(l.elemSpec)
        s"java.util.List<$elemJavaType>"
      }
  }

  private def toObjectType(spec: Spec): String = {
    spec match {
      case a: AtomicSpec ⇒
        a.typ match {
          case STRING   ⇒ "java.lang.String"
          case INTEGER  ⇒ "java.lang.Integer"
          case LONG     ⇒ "java.lang.Long"
          case DOUBLE   ⇒ "java.lang.Double"
          case BOOLEAN  ⇒ "java.lang.Boolean"
          case DURATION ⇒ "java.lang.Long"
        }

      case o: ObjSpec  ⇒
        getClassName(o.name)

      case l: ListSpec  ⇒
        val elemJavaType = toObjectType(l.elemSpec)
        s"java.util.List<$elemJavaType>"
    }
  }

  private def instance(spec: Spec, path: String): String = {
    spec match {
      case a: AtomicSpec ⇒
        a.typ match {
          case STRING ⇒
            if (spec.defaultValue.isDefined) {
              val value = spec.defaultValue.get
              s"""c != null && c.hasPath("$path") ? c.getString("$path") : "$value""""
            }
            else if (spec.isOptional) {
              s"""c != null && c.hasPath("$path") ? c.getString("$path") : null"""
            }
            else
              s"""c.getString("$path")"""

          case INTEGER ⇒
            if (spec.defaultValue.isDefined) {
              val value = spec.defaultValue.get
              s"""c != null && c.hasPath("$path") ? c.getInt("$path") : $value"""
            }
            else if (spec.isOptional) {
              s"""c != null && c.hasPath("$path") ? c.getInt("$path") : null"""
            }
            else
              s"""c.getInt("$path")"""

          case LONG ⇒
            if (spec.defaultValue.isDefined) {
              val value = spec.defaultValue.get
              s"""c != null && c.hasPath("$path") ? c.getLong("$path") : $value"""
            }
            else if (spec.isOptional) {
              s"""c != null && c.hasPath("$path") ? c.getLong("$path") : null"""
            }
            else
              s"""c.getLong("$path")"""

          case DOUBLE ⇒
            if (spec.defaultValue.isDefined) {
              val value = spec.defaultValue.get
              s"""c != null && c.hasPath("$path") ? c.getDouble("$path") : $value"""
            }
            else if (spec.isOptional) {
              s"""c != null && c.hasPath("$path") ? c.getDouble("$path") : null"""
            }
            else
              s"""c.getDouble("$path")"""

          case BOOLEAN ⇒
            if (spec.defaultValue.isDefined) {
              val value = spec.defaultValue.get
              s"""c != null && c.hasPath("$path") ? c.getBoolean("$path") : $value"""
            }
            else if (spec.isOptional) {
              s"""c != null && c.hasPath("$path") ? c.getBoolean("$path") : null"""
            }
            else
              s"""c.getBoolean("$path")"""


          case DURATION ⇒ s"""TODO_getDuration("$path")"""
        }

      case o: ObjSpec  ⇒
        s"""new ${getClassName(o.name)}(_$$config(c, "$path"))"""

      case l: ListSpec  ⇒
        accessors._listName(l.elemSpec) + s"""(c.getList("$path"))"""
    }
  }

  private object accessors {
    // defined in terms of corresponding elemAccessor:
    type JavaElemTypeAndAccessor = (String,String)
    val definedListElemAccessors = collection.mutable.HashSet[JavaElemTypeAndAccessor]()

    def _listName(spec: Spec): String = {
      val elemAccessor = spec match {
        case a: AtomicSpec ⇒
          a.typ match {
            case STRING   ⇒ "$str"
            case INTEGER  ⇒ "$int"
            case LONG     ⇒ "$lng"
            case DOUBLE   ⇒ "$dbl"
            case BOOLEAN  ⇒ "$bol"
            case DURATION ⇒ "$dur"
          }

        case o: ObjSpec  ⇒ getClassName(o.name)

        case l: ListSpec ⇒ _listName(l.elemSpec)
      }
      val javaType = toObjectType(spec)
      definedListElemAccessors += ((javaType, elemAccessor))
      "$list" + elemAccessor
    }

    def _list(elemJavaType: String, elemAccessor: String): String = {
      val elem = if (elemAccessor.startsWith("$list"))
        s"$elemAccessor((com.typesafe.config.ConfigList)cv)"
      else if (elemAccessor.startsWith("$"))
          s"$elemAccessor(cv)"
      else
          s"new $elemAccessor(((com.typesafe.config.ConfigObject)cv).toConfig())"

      s"""
         |private static java.util.List<$elemJavaType> $$list$elemAccessor(com.typesafe.config.ConfigList cl) {
         |  java.util.ArrayList<$elemJavaType> al = new java.util.ArrayList<$elemJavaType>();
         |  for (com.typesafe.config.ConfigValue cv: cl) {
         |    al.add($elem);
         |  }
         |  return java.util.Collections.unmodifiableList(al);
         |}""".stripMargin
    }

    def _int(): String = {
      """
        |private static java.lang.Integer $int(com.typesafe.config.ConfigValue cv) {
        |  java.lang.Object u = cv.unwrapped();
        |  if (cv.valueType() != com.typesafe.config.ConfigValueType.NUMBER
        |      || !(u instanceof java.lang.Integer)) {
        |    _$exc(u, "integer");
        |  }
        |  return (java.lang.Integer) u;
        |}""".stripMargin
    }

    def _exc(): String = {
      """
        |private static void _$exc(java.lang.Object u, java.lang.String expected) {
        |  throw new java.lang.RuntimeException(
        |      "expecting: " +expected + " got: " +
        |          (u instanceof java.lang.String ? "\"" +u+ "\"" : u));
        |}""".stripMargin
    }

    val configGetter = s"""
      |private static $TypesafeConfigClassName _$$config($TypesafeConfigClassName c, java.lang.String path) {
      |  return c != null && c.hasPath(path) ? c.getConfig(path) : null;
      |}""".stripMargin

    def insertAuxMethods(code:Code, isRoot: Boolean, indent: String, results: GenResult): Unit = {
      definedListElemAccessors foreach { case (javaType, elemAccessor) ⇒
        println(s" --- $javaType  :  $elemAccessor")
        code.println(accessors._list(javaType, elemAccessor).replaceAll("\n", "\n" + indent))
      }
      code.println(accessors._int().replaceAll("\n", "\n" + indent))
      code.println(accessors._exc().replaceAll("\n", "\n" + indent))
      if (isRoot && results.classNames.size > 1) {
        code.println(accessors.configGetter.replaceAll("\n", "\n" + indent))
      }
    }
  }
}

object JavaGenerator {
  import com.typesafe.config.ConfigFactory
  import tscfg.SpecBuilder
  import java.io.File

  def main(args: Array[String]): Unit = {
    val filename = args(0)
    val file = new File(filename)
    val src = io.Source.fromFile(file).mkString.trim
    println("src:\n  |" + src.replaceAll("\n", "\n  |"))
    val config = ConfigFactory.parseString(src).resolve()

    val className = "Java" + {
      val noPath = filename.substring(filename.lastIndexOf('/') + 1)
      val noDef = noPath.replaceAll("""^def\.""", "")
      val symbol = noDef.substring(0, noDef.indexOf('.'))
      symbol.charAt(0).toUpper + symbol.substring(1) + "Cfg"
    }

    val objSpec = SpecBuilder.fromConfig(config, className)
    println("\nobjSpec:\n  |" + objSpec.format().replaceAll("\n", "\n  |"))

    implicit val genOpts = GenOpts("tscfg.example", className,
      preamble = Some(s"source: (a test)")
    )

    val generator: Generator = new JavaGenerator

    val results = generator.generate(objSpec)

    println("\n" + results.code)

    val destFilename  = s"src/main/java/tscfg/example/$className.java"
    val destFile = new File(destFilename)
    val out = new PrintWriter(new FileWriter(destFile), true)
    out.println(results.code)
  }
}
