// generated by tscfg 0.3.4 on Sat Nov 19 11:07:01 PST 2016
// source: example/issue14.conf

package tscfg.example

object ScalaIssue14Cfg {
  object _0 {
    def apply(c: com.typesafe.config.Config) = build(Some(c))
    def apply() = build(None)
    def build(c: scala.Option[com.typesafe.config.Config]): _0 = {
      _0(
        c.map(c => if(c.hasPathOrNull("1")) c.getString("1") else "bar").get
      )
    }
  }
  case class _0(
    _1 : java.lang.String
  ) {
    override def toString: java.lang.String = toString("")
    def toString(i:java.lang.String): java.lang.String = {
      i+ "1 = " + this._1 + "\n"
    }
  }
  def apply(c: com.typesafe.config.Config) = build(Some(c))
  def apply() = build(None)
  def build(c: scala.Option[com.typesafe.config.Config]): ScalaIssue14Cfg = {
    ScalaIssue14Cfg(
      _0.build(c.map(c => if (c.hasPath("0")) Some(c.getConfig("0")) else None).get),
      c.map(c => if(c.hasPathOrNull("2")) c.getString("2") else "foo").get
    )
  }
}
case class ScalaIssue14Cfg(
  _0 : ScalaIssue14Cfg._0,
  _2 : java.lang.String
) {
  override def toString: java.lang.String = toString("")
  def toString(i:java.lang.String): java.lang.String = {
    i+ "0:\n" + this._0.toString(i+"    ")+
    i+ "2 = " + this._2 + "\n"
  }
}
