// generated by tscfg 0.3.3 on Thu Aug 25 22:26:32 PDT 2016
// source: example/issue11.conf

package tscfg.example

object ScalaIssue11Cfg {
  object Foo {
    def apply(c: scala.Option[com.typesafe.config.Config]): Foo = {
      Foo(
        c.map(c => if(c.hasPathOrNull("clone")) c.getString("clone") else "..").get,
        c.map(c => if(c.hasPathOrNull("finalize")) c.getString("finalize") else "..").get,
        c.map(c => if(c.hasPathOrNull("getClass")) c.getString("getClass") else "..").get,
        c.map(c => if(c.hasPathOrNull("notify")) c.getString("notify") else "..").get,
        c.map(c => if(c.hasPathOrNull("notifyAll")) c.getString("notifyAll") else "..").get,
        c.map(c => if(c.hasPathOrNull("toString")) c.getString("toString") else "..").get,
        c.map(c => if(c.hasPathOrNull("wait")) c.getString("wait") else "..").get
      )
    }
  }
  case class Foo(
    clone_     : String,
    finalize_  : String,
    getClass_  : String,
    notify_    : String,
    notifyAll_ : String,
    toString_  : String,
    wait_      : String
  ) {
    override def toString: String = toString("")
    def toString(i:String): String = {
      i+ "clone     = " + '"' + this.clone_ + '"' + "\n"+
      i+ "finalize  = " + '"' + this.finalize_ + '"' + "\n"+
      i+ "getClass  = " + '"' + this.getClass_ + '"' + "\n"+
      i+ "notify    = " + '"' + this.notify_ + '"' + "\n"+
      i+ "notifyAll = " + '"' + this.notifyAll_ + '"' + "\n"+
      i+ "toString  = " + '"' + this.toString_ + '"' + "\n"+
      i+ "wait      = " + '"' + this.wait_ + '"' + "\n"
    }
  }
  def apply(c: scala.Option[com.typesafe.config.Config]): ScalaIssue11Cfg = {
    ScalaIssue11Cfg(
      Foo(c.map(c => if (c.hasPath("foo")) Some(c.getConfig("foo")) else None).get)
    )
  }
}
case class ScalaIssue11Cfg(
  foo : ScalaIssue11Cfg.Foo
) {
  override def toString: String = toString("")
  def toString(i:String): String = {
    i+ "foo:\n" + this.foo.toString(i+"    ")
  }
}
