// generated by tscfg 0.3.3 on Thu Aug 25 22:26:32 PDT 2016
// source: example/example0.spec.conf

package tscfg.example

object ScalaExample0Cfg {
  object Service {
    def apply(c: scala.Option[com.typesafe.config.Config]): Service = {
      Service(
        c.map(c => if(c.hasPathOrNull("debug")) c.getBoolean("debug") else true).get,
        c.map(c => if(c.hasPathOrNull("factor")) c.getDouble("factor") else 0.75).get,
        c.map(c => if(c.hasPathOrNull("poolSize")) c.getInt("poolSize") else 32).get,
        c.map(c => if(c.hasPathOrNull("url")) c.getString("url") else "http://example.net/rest").get
      )
    }
  }
  case class Service(
    debug    : Boolean,
    factor   : Double,
    poolSize : Int,
    url      : String
  ) {
    override def toString: String = toString("")
    def toString(i:String): String = {
      i+ "debug    = " + this.debug + "\n"+
      i+ "factor   = " + this.factor + "\n"+
      i+ "poolSize = " + this.poolSize + "\n"+
      i+ "url      = " + '"' + this.url + '"' + "\n"
    }
  }
  def apply(c: scala.Option[com.typesafe.config.Config]): ScalaExample0Cfg = {
    ScalaExample0Cfg(
      Service(c.map(c => if (c.hasPath("service")) Some(c.getConfig("service")) else None).get)
    )
  }
}
case class ScalaExample0Cfg(
  service : ScalaExample0Cfg.Service
) {
  override def toString: String = toString("")
  def toString(i:String): String = {
    i+ "service:\n" + this.service.toString(i+"    ")
  }
}
