// generated by tscfg 0.3.3 on Thu Aug 25 20:49:05 PDT 2016
// source: example/example1.spec.conf

package tscfg.example

object ScalaExample1Cfg {
  def apply(c: scala.Option[com.typesafe.config.Config]): ScalaExample1Cfg = {
    ScalaExample1Cfg(
      c.map(c => if(c.hasPathOrNull("bazOptionalWithDefault")) c.getString("bazOptionalWithDefault") else "hello").get,
      c.map(c => if(c.hasPathOrNull("bazOptionalWithNoDefault")) Some(c.getString("bazOptionalWithNoDefault")) else None).get,
      c.get.getString("fooRequired")
    )
  }
}
case class ScalaExample1Cfg(
  bazOptionalWithDefault   : String,
  bazOptionalWithNoDefault : Option[String],
  fooRequired              : String
) {
  override def toString: String = toString("")
  def toString(i:String): String = {
    i+ "bazOptionalWithDefault   = " + '"' + this.bazOptionalWithDefault + '"' + "\n"+
    i+ "bazOptionalWithNoDefault = " + (if(this.bazOptionalWithNoDefault.isDefined) "Some(" +'"' +this.bazOptionalWithNoDefault.get+ '"' + ")" else "None") + "\n"+
    i+ "fooRequired              = " + '"' + this.fooRequired + '"' + "\n"
  }
}
