// generated by tscfg 0.3.3 on Thu Aug 25 22:26:32 PDT 2016
// source: example/def.example.conf

package tscfg.example

object ScalaExampleCfg {
  object Endpoint {
    object Interface {
      def apply(c: scala.Option[com.typesafe.config.Config]): Interface = {
        Interface(
          c.map(c => if(c.hasPathOrNull("port")) c.getInt("port") else 8080).get,
          c.map(c => if(c.hasPathOrNull("type")) Some(c.getString("type")) else None).get
        )
      }
    }
    case class Interface(
      port   : Int,
      `type` : Option[String]
    ) {
      override def toString: String = toString("")
      def toString(i:String): String = {
        i+ "port = " + this.port + "\n"+
        i+ "type = " + (if(this.`type`.isDefined) "Some(" +'"' +this.`type`.get+ '"' + ")" else "None") + "\n"
      }
    }
    def apply(c: scala.Option[com.typesafe.config.Config]): Endpoint = {
      Endpoint(
        c.get.getInt("intReq"),
        Interface(c.map(c => if (c.hasPath("interface")) Some(c.getConfig("interface")) else None).get),
        c.get.getString("path"),
        c.map(c => if(c.hasPathOrNull("serial")) Some(c.getInt("serial")) else None).get,
        c.map(c => if(c.hasPathOrNull("url")) c.getString("url") else "http://example.net").get
      )
    }
  }
  case class Endpoint(
    intReq    : Int,
    interface : ScalaExampleCfg.Endpoint.Interface,
    path      : String,
    serial    : Option[Int],
    url       : String
  ) {
    override def toString: String = toString("")
    def toString(i:String): String = {
      i+ "intReq    = " + this.intReq + "\n"+
      i+ "interface:\n" + this.interface.toString(i+"    ")+
      i+ "path      = " + '"' + this.path + '"' + "\n"+
      i+ "serial    = " + this.serial + "\n"+
      i+ "url       = " + '"' + this.url + '"' + "\n"
    }
  }
  def apply(c: scala.Option[com.typesafe.config.Config]): ScalaExampleCfg = {
    ScalaExampleCfg(
      Endpoint(c.map(c => if (c.hasPath("endpoint")) Some(c.getConfig("endpoint")) else None).get)
    )
  }
}
case class ScalaExampleCfg(
  endpoint : ScalaExampleCfg.Endpoint
) {
  override def toString: String = toString("")
  def toString(i:String): String = {
    i+ "endpoint:\n" + this.endpoint.toString(i+"    ")
  }
}
