// generated by tscfg 0.3.0 on Tue Mar 01 23:12:30 PST 2016
// source: example/example-duration.spec.conf

package tscfg.example

object ScalaExampleDurationCfg {
  object Durations {
    def apply(c: com.typesafe.config.Config): Durations = {
      Durations(
        if(c.hasPathOrNull("days")) Some(c.getDuration("days", java.util.concurrent.TimeUnit.DAYS)) else None,
        c.getDuration("hours", java.util.concurrent.TimeUnit.HOURS),
        if(c.hasPathOrNull("millis")) c.getDuration("millis", java.util.concurrent.TimeUnit.MILLISECONDS) else 550000
      )
    }
  }
  case class Durations(
    days : Option[Long],
    hours : Long,
    millis : Long
  ) {
    override def toString: String = toString("")
    def toString(i:String): String = {
      i+ "days = " + this.days + "\n"+
      i+ "hours = " + this.hours + "\n"+
      i+ "millis = " + this.millis + "\n"
    }
  }
  def apply(c: com.typesafe.config.Config): ScalaExampleDurationCfg = {
    ScalaExampleDurationCfg(
      Durations(c.getConfig("durations"))
    )
  }
}
case class ScalaExampleDurationCfg(
  durations : ScalaExampleDurationCfg.Durations
) {
  override def toString: String = toString("")
  def toString(i:String): String = {
    i+ "Durations(\n" + this.durations.toString(i+"    ") +i+ ")\n"
  }
}
