// generated by tscfg 0.3.1 on Tue Aug 16 09:09:51 PDT 2016
// source: example/issue11.conf

package tscfg.example

object ScalaIssue11Cfg {
  object Foo {
    def apply(c: com.typesafe.config.Config): Foo = {
      Foo(
        if(c.hasPathOrNull("clone")) c.getString("clone") else "..",
        if(c.hasPathOrNull("finalize")) c.getString("finalize") else "..",
        if(c.hasPathOrNull("getClass")) c.getString("getClass") else "..",
        if(c.hasPathOrNull("notify")) c.getString("notify") else "..",
        if(c.hasPathOrNull("notifyAll")) c.getString("notifyAll") else "..",
        if(c.hasPathOrNull("toString")) c.getString("toString") else "..",
        if(c.hasPathOrNull("wait")) c.getString("wait") else ".."
      )
    }
  }
  case class Foo(
    clone_     : String,
    finalize_  : String,
    getClass_  : String,
    notify_    : String,
    notifyAll_ : String,
    toString_  : String,
    wait_      : String
  ) {
    override def toString: String = toString("")
    def toString(i:String): String = {
      i+ "clone     = " + '"' + this.clone_ + '"' + "\n"+
      i+ "finalize  = " + '"' + this.finalize_ + '"' + "\n"+
      i+ "getClass  = " + '"' + this.getClass_ + '"' + "\n"+
      i+ "notify    = " + '"' + this.notify_ + '"' + "\n"+
      i+ "notifyAll = " + '"' + this.notifyAll_ + '"' + "\n"+
      i+ "toString  = " + '"' + this.toString_ + '"' + "\n"+
      i+ "wait      = " + '"' + this.wait_ + '"' + "\n"
    }
  }
  def apply(c: com.typesafe.config.Config): ScalaIssue11Cfg = {
    ScalaIssue11Cfg(
      Foo(c.getConfig("foo"))
    )
  }
}
case class ScalaIssue11Cfg(
  foo : ScalaIssue11Cfg.Foo
) {
  override def toString: String = toString("")
  def toString(i:String): String = {
    i+ "foo:\n" + this.foo.toString(i+"    ")
  }
}
