// generated by tscfg 0.3.3 on Thu Sep 01 11:12:22 PDT 2016
// source: example/example0.spec.conf

package tscfg.example

object ScalaExample0Cfg {
  object Service {
    def apply(c: com.typesafe.config.Config) = build(Some(c))
    def apply() = build(None)
    def build(c: scala.Option[com.typesafe.config.Config]): Service = {
      Service(
        c.map(c => if(c.hasPathOrNull("debug")) c.getBoolean("debug") else true).get,
        c.map(c => if(c.hasPathOrNull("factor")) c.getDouble("factor") else 0.75).get,
        c.map(c => if(c.hasPathOrNull("poolSize")) c.getInt("poolSize") else 32).get,
        c.map(c => if(c.hasPathOrNull("url")) c.getString("url") else "http://example.net/rest").get
      )
    }
  }
  case class Service(
    debug    : scala.Boolean,
    factor   : scala.Double,
    poolSize : scala.Int,
    url      : java.lang.String
  ) {
    override def toString: java.lang.String = toString("")
    def toString(i:java.lang.String): java.lang.String = {
      i+ "debug    = " + this.debug + "\n"+
      i+ "factor   = " + this.factor + "\n"+
      i+ "poolSize = " + this.poolSize + "\n"+
      i+ "url      = " + this.url + "\n"
    }
  }
  def apply(c: com.typesafe.config.Config) = build(Some(c))
  def apply() = build(None)
  def build(c: scala.Option[com.typesafe.config.Config]): ScalaExample0Cfg = {
    ScalaExample0Cfg(
      Service.build(c.map(c => if (c.hasPath("service")) Some(c.getConfig("service")) else None).get)
    )
  }
}
case class ScalaExample0Cfg(
  service : ScalaExample0Cfg.Service
) {
  override def toString: java.lang.String = toString("")
  def toString(i:java.lang.String): java.lang.String = {
    i+ "service:\n" + this.service.toString(i+"    ")
  }
}
