// generated by tscfg 0.3.3 on Thu Sep 01 11:12:22 PDT 2016
// source: example/issue13.conf

package tscfg.example

object ScalaIssue13Cfg {
  object Issue {
    def apply(c: com.typesafe.config.Config) = build(Some(c))
    def apply() = build(None)
    def build(c: scala.Option[com.typesafe.config.Config]): Issue = {
      Issue(
        c.map(c => if(c.hasPathOrNull("optionalFoo")) Some(c.getString("optionalFoo")) else None).get
      )
    }
  }
  case class Issue(
    optionalFoo : scala.Option[java.lang.String]
  ) {
    override def toString: java.lang.String = toString("")
    def toString(i:java.lang.String): java.lang.String = {
      i+ "optionalFoo = " + this.optionalFoo + "\n"
    }
  }
  def apply(c: com.typesafe.config.Config) = build(Some(c))
  def apply() = build(None)
  def build(c: scala.Option[com.typesafe.config.Config]): ScalaIssue13Cfg = {
    ScalaIssue13Cfg(
      Issue.build(c.map(c => if (c.hasPath("issue")) Some(c.getConfig("issue")) else None).get)
    )
  }
}
case class ScalaIssue13Cfg(
  issue : ScalaIssue13Cfg.Issue
) {
  override def toString: java.lang.String = toString("")
  def toString(i:java.lang.String): java.lang.String = {
    i+ "issue:\n" + this.issue.toString(i+"    ")
  }
}
