// generated by tscfg 0.3.3 on Thu Aug 25 23:25:59 PDT 2016
// source: example/example-duration.spec.conf

package tscfg.example

object ScalaExampleDurationCfg {
  object Durations {
    def apply(c: scala.Option[com.typesafe.config.Config]): Durations = {
      Durations(
        c.map(c => if(c.hasPathOrNull("days")) Some(c.getDuration("days", java.util.concurrent.TimeUnit.DAYS)) else None).get,
        c.map(c => c.getDuration("hours", java.util.concurrent.TimeUnit.HOURS)).get,
        c.map(c => if(c.hasPathOrNull("millis")) c.getDuration("millis", java.util.concurrent.TimeUnit.MILLISECONDS) else 550000).get
      )
    }
  }
  case class Durations(
    days   : scala.Option[scala.Long],
    hours  : scala.Long,
    millis : scala.Long
  ) {
    override def toString: java.lang.String = toString("")
    def toString(i:java.lang.String): java.lang.String = {
      i+ "days   = " + this.days + "\n"+
      i+ "hours  = " + this.hours + "\n"+
      i+ "millis = " + this.millis + "\n"
    }
  }
  def apply(c: scala.Option[com.typesafe.config.Config]): ScalaExampleDurationCfg = {
    ScalaExampleDurationCfg(
      Durations(c.map(c => if (c.hasPath("durations")) Some(c.getConfig("durations")) else None).get)
    )
  }
}
case class ScalaExampleDurationCfg(
  durations : ScalaExampleDurationCfg.Durations
) {
  override def toString: java.lang.String = toString("")
  def toString(i:java.lang.String): java.lang.String = {
    i+ "durations:\n" + this.durations.toString(i+"    ")
  }
}
